import { Project } from '@/types';

// All projects - for Work page
export const allProjects: Project[] = [
  // Featured AI Products (User's actual projects)
  {
    id: '1',
    title: 'Tailr AI',
    slug: 'tailr-ai',
    description: 'Resume optimiser that beats ATS filters without inventing facts. Drop your resume + job link → Get tailored resume in under 30 seconds. Turning a 2-hour application into a 2-minute workflow.',
    image: '',
    technologies: ['AI', 'Gemini', 'Product Design', 'Automation'],
    services: ['AI Development', 'Product Design', 'Automation'],
    category: 'both',
    year: 2024,
    location: 'India',
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: '2',
    title: 'Recall',
    slug: 'recall',
    description: 'AI Study Assistant living inside WhatsApp & Telegram. Save lectures, PDFs, links → Recall organizes, tags, and generates instant audio/video explainers on command. Your study bookmarks, reimagined as a personal tutor.',
    image: '',
    technologies: ['AI', 'WhatsApp Bot', 'Telegram', 'Learning Tech'],
    services: ['AI Development', 'Bot Development', 'Learning Tech'],
    category: 'development',
    year: 2024,
    location: 'India',
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: '3',
    title: 'F1 Pitwall',
    slug: 'f1-pitwall',
    description: 'Telemetry Reimagined for F1 fans. Talk to race data like an engineer. Get technical, data-backed answers: "Why is Lewis losing time in Sector 2?" The ultimate second-screen for the world\'s most data-rich sport.',
    image: '',
    technologies: ['AI', 'Gemini', 'Data Analytics', 'Sports Tech'],
    services: ['AI Development', 'Data Analytics', 'Sports Tech'],
    category: 'development',
    year: 2024,
    location: 'India',
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: '4',
    title: 'Kathy',
    slug: 'kathy',
    description: 'Personal Diet Specialist on WhatsApp with zero friction. Snap a meal photo → Kathy identifies food, estimates portions, calculates macros instantly. Like a nutritionist who texts back before you eat it.',
    image: '',
    technologies: ['AI', 'WhatsApp Bot', 'Computer Vision', 'Health Tech'],
    services: ['AI Development', 'Computer Vision', 'Health Tech'],
    category: 'development',
    year: 2024,
    location: 'India',
    liveUrl: '#',
    githubUrl: '#',
  },
  // Additional projects to reach 11 featured
  {
    id: '5',
    title: 'Market Intelligence Dashboard',
    slug: 'market-intelligence-dashboard',
    description: 'Enterprise-grade analytics platform for global market trends. Real-time data visualization and predictive insights for strategic decision making.',
    image: '',
    technologies: ['Data Analytics', 'Visualization', 'Enterprise'],
    services: ['Data Analytics', 'Dashboard Design', 'Development'],
    category: 'both',
    year: 2024,
    location: 'India',
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: '6',
    title: 'AI Workflow Automation Suite',
    slug: 'ai-workflow-automation',
    description: 'Custom automation tools that eliminate repetitive tasks across business workflows. Smart integration with existing tools and systems.',
    image: '',
    technologies: ['AI', 'Automation', 'Integration'],
    services: ['AI Development', 'Automation', 'Integration'],
    category: 'development',
    year: 2023,
    location: 'India',
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: '7',
    title: 'Product Analytics Engine',
    slug: 'product-analytics-engine',
    description: 'Advanced analytics system for product teams. Track user behavior, feature adoption, and conversion funnels with AI-powered insights.',
    image: '',
    technologies: ['Analytics', 'AI', 'Product'],
    services: ['Data Analytics', 'AI Development', 'Product Design'],
    category: 'both',
    year: 2023,
    location: 'India',
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: '8',
    title: 'Content Generation Platform',
    slug: 'content-generation-platform',
    description: 'AI-powered content creation tool for marketers and creators. Generate blog posts, social media content, and marketing copy that matches your brand voice.',
    image: '',
    technologies: ['AI', 'NLP', 'Content'],
    services: ['AI Development', 'Product Design', 'Content Tech'],
    category: 'both',
    year: 2023,
    location: 'India',
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: '9',
    title: 'Smart Document Parser',
    slug: 'smart-document-parser',
    description: 'Intelligent document processing system. Extract structured data from PDFs, contracts, and invoices with high accuracy using computer vision and NLP.',
    image: '',
    technologies: ['AI', 'Computer Vision', 'NLP'],
    services: ['AI Development', 'Document Processing'],
    category: 'development',
    year: 2023,
    location: 'India',
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: '10',
    title: 'Voice Assistant Integration',
    slug: 'voice-assistant-integration',
    description: 'Custom voice interface for enterprise applications. Natural language processing for hands-free interaction with complex systems.',
    image: '',
    technologies: ['AI', 'Voice', 'NLP'],
    services: ['AI Development', 'Voice Interface', 'Integration'],
    category: 'development',
    year: 2023,
    location: 'India',
    liveUrl: '#',
    githubUrl: '#',
  },
  {
    id: '11',
    title: 'Predictive Maintenance System',
    slug: 'predictive-maintenance-system',
    description: 'ML-powered system for predicting equipment failures before they happen. Reduces downtime and maintenance costs through intelligent monitoring.',
    image: '',
    technologies: ['AI', 'Machine Learning', 'IoT'],
    services: ['AI Development', 'Data Analytics', 'IoT'],
    category: 'development',
    year: 2023,
    location: 'India',
    liveUrl: '#',
    githubUrl: '#',
  },
];

// Featured projects for homepage (first 4)
export const featuredProjects = allProjects.slice(0, 4);

// Filter projects by category
export const filterProjects = (category?: 'design' | 'development' | 'all') => {
  if (!category || category === 'all') {
    return allProjects;
  }
  return allProjects.filter(project =>
    project.category === category || project.category === 'both'
  );
};
